config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :haunted_houses, only: [:show] do
    resources :monsters, only: [:new, :create]
  end
  resources :monsters, only: [:destroy] do
    resources :curses, only: [:new, :create]
  end
end

# haunted_houses#show
# monsters#new
# monsters#create
# monsters#destroy
# curses#new
# /monsters/:monster_id/curses/new
# curses#create
# /monsters/:monster_id/curses

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curse.rb
class Curse < ApplicationRecord
  belongs_to :monster
  belongs_to :power
  validates :power, uniqueness: { scope: :monster }
end

app/models/haunted_house.rb
class HauntedHouse < ApplicationRecord
  has_many :monsters, dependent: :destroy # haunted_house.monsters
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :haunted_house
  has_many :curses, dependent: :destroy
  has_many :powers, through: :curses
  has_one_attached :photo
  validates :name, presence: true
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :curses # invincibility.curses
  has_many :monsters, through: :curses # invincibility.monsters
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curses_controller.rb
class CursesController < ApplicationController
  def new
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new
    @powers = Power.where.not(id: @monster.powers).order(name: :asc)
  end

  def create
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new(curse_params)
    @curse.monster = @monster
    if @curse.save
      redirect_to haunted_house_path(@monster.haunted_house)
    else
      @powers = Power.where.not(id: @monster.powers).order(name: :asc) # for the form
      render :new
    end
  end

  private

  def curse_params
    params.require(:curse).permit(:power_id)
  end
end

app/controllers/haunted_houses_controller.rb
class HauntedHousesController < ApplicationController
  def show
    @haunted_house = HauntedHouse.find(params[:id])
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_haunted_house, only: [:new, :create]

  def new
    @monster = Monster.new # for the form
  end

  def create
    @monster = Monster.new(monster_params)
    @monster.haunted_house = @haunted_house
    if @monster.save
      redirect_to haunted_house_path(@haunted_house)
    else
      render :new
    end
  end

  def destroy
    @monster = Monster.find(params[:id])
    @monster.destroy
    redirect_to haunted_house_path(@monster.haunted_house)
  end

  private

  def monster_params
    params.require(:monster).permit(:name, :image_url, :photo)
  end

  def set_haunted_house
    @haunted_house = HauntedHouse.find(params[:haunted_house_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curses_helper.rb
module CursesHelper
end

app/helpers/haunted_houses_helper.rb
module HauntedHousesHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/curses/new.html.erb
<div class="container mt-5">
  <h1>Add Power</h1>
  <%= simple_form_for [@monster, @curse] do |f| %>
    <%= f.association :power, collection: @powers, include_blank: false %>
    <%= f.submit 'Submit', class: 'btn btn-danger' %>
  <% end %>
  <small><%= link_to 'Back', haunted_house_path(@monster.haunted_house), class: 'btn-light' %></small>
</div>

app/views/haunted_houses/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @haunted_house.banner_url %>);">
  <div class="container">
    <h1><%= @haunted_house.name %></h1>
    <%= link_to "Add Monster", new_haunted_house_monster_path(@haunted_house), class: 'btn btn-danger mt-2' %>
  </div>
</div>
<%= cl_image_tag(@haunted_house.monsters.last.photo.key,
      width: 300, height: 300, crop: :thumb, gravity: :face) %>
<div class="container mt-3 mb-5">
  <div class="cards">
    <% @haunted_house.monsters.each do |monster| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= monster.photo.attached? ? cl_image_path(monster.photo.key) : monster.image_url %>)">
        <%= monster.name %>
        <%= link_to monster_path(monster), class: 'card-remove-link', method: :delete, data: { confirm: "Remove #{monster.name}?" } do %>
          <i class="fas fa-meteor"></i>
        <% end %>
        <%= link_to new_monster_curse_path(monster), class: 'card-link' do  %>
          <i class="fas fa-magic"></i>
        <% end %>
        <div class="card-tags">
          <% monster.powers.each do |power| %>
            <span><%= power.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HauntedHouse858</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/new.html.erb
<div class="container">
  <h1>Spawn a Monster</h1>
  <%= simple_form_for [@haunted_house, @monster] do |f| %>
    <%= f.input :name %>
    <%# This is the OLD way %>
    <%#= f.input :image_url %>
    <%# Using ActiveStorage %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Add', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>